import { Student } from '../types/student.type';

export const initialStudents: Student[] = [
  {
    id: 'STU-001',
    name: 'Ahmed Khan',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed',
    age: 14,
    grade: 'Grade 8',
    guardian: 'Fatima Khan',
    guardianPhone: '+1 (555) 123-4567',
    enrollmentDate: 'Sep 1, 2023',
    status: 'active',
    attendance: 94,
    cpf: '123.456.789-00',
    race: 'parda',
    placeOfBirth: 'São Paulo, SP',
    fatherName: 'Hassan Khan',
    motherName: 'Fatima Khan',
    enrollmentOrigin: 'community',
    accompaniedStatus: 'accompanied',
    medicalData: {
      physicalActivityRestrictions: 'Mild asthma - may need breaks during intense exercise',
      dietaryRestrictions: 'Lactose intolerant - no dairy products',
      disabilities: '',
      dentalCare: true,
      ophthalmologicalCare: false,
      allergies: 'Peanuts (severe), shellfish',
    },
    familyData: {
      members: [
        {
          id: 'fm-1',
          name: 'Fatima Khan',
          relationship: 'Mother',
          profession: 'Seamstress',
          income: '1,200',
        },
        {
          id: 'fm-2',
          name: 'Hassan Khan',
          relationship: 'Father',
          profession: 'Delivery Driver',
          income: '1,800',
        },
        {
          id: 'fm-3',
          name: 'Sara Khan',
          relationship: 'Sister',
          profession: 'Student',
          income: '',
        },
      ],
      maritalStatus: 'married',
      separated: false,
      contactWithSeparatedSpouse: 'no',
      contactFrequency: '',
      housingType: 'rented',
      benefits: {
        bolsaFamilia: true,
        rendaCidada: false,
        bpc: false,
        other: '',
      },
      familyAssessment:
        'Family is stable and supportive. Both parents work full-time to support the household. Ahmed shows good academic potential and receives encouragement from his family. The family manages finances carefully despite modest income.',
      activities: [
        {
          id: 'act-1',
          name: 'Soccer',
          category: 'sports',
          days: ['Tuesday', 'Thursday'],
          organization: 'Community Sports Center',
        },
        {
          id: 'act-2',
          name: 'Quran Studies',
          category: 'culture',
          days: ['Saturday'],
          organization: 'Local Mosque',
        },
      ],
      socialRisk: {
        childProtectiveServices: false,
        prisonSystem: false,
        policeStation: false,
        emergencyRoom: false,
        rehabilitationCenter: false,
        womensPoliceStation: false,
        otherServices: '',
        hasPrioritySituation: false,
        situationCode: '',
        observations: '',
      },
    },
  },
  {
    id: 'STU-002',
    name: 'Maria Santos',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    age: 12,
    grade: 'Grade 6',
    guardian: 'Carlos Santos',
    guardianPhone: '+1 (555) 234-5678',
    enrollmentDate: 'Sep 1, 2022',
    status: 'active',
    attendance: 88,
  },
  {
    id: 'STU-003',
    name: 'David Chen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    age: 15,
    grade: 'Grade 9',
    guardian: 'Linda Chen',
    guardianPhone: '+1 (555) 345-6789',
    enrollmentDate: 'Jan 15, 2024',
    status: 'active',
    attendance: 96,
    medicalData: {
      physicalActivityRestrictions: '',
      dietaryRestrictions: 'Vegetarian diet',
      disabilities: '',
      dentalCare: true,
      ophthalmologicalCare: true,
      allergies: '',
    },
    familyData: {
      members: [
        {
          id: 'fm-9',
          name: 'Linda Chen',
          relationship: 'Mother',
          profession: 'Software Engineer',
          income: '5,800',
        },
        {
          id: 'fm-10',
          name: 'Robert Chen',
          relationship: 'Father',
          profession: 'Architect',
          income: '6,200',
        },
      ],
      maritalStatus: 'married',
      separated: false,
      contactWithSeparatedSpouse: 'no',
      contactFrequency: '',
      housingType: 'own',
      benefits: {
        bolsaFamilia: false,
        rendaCidada: false,
        bpc: false,
        other: '',
      },
      familyAssessment:
        "Stable two-parent household with strong emphasis on education. Both parents are highly educated professionals who actively support David's academic pursuits. Family maintains cultural traditions while encouraging integration. David is a high achiever with good study habits.",
      activities: [
        {
          id: 'act-7',
          name: 'Robotics Club',
          category: 'socio-educational',
          days: ['Wednesday', 'Friday'],
          organization: 'Tech Youth Academy',
        },
        {
          id: 'act-8',
          name: 'Basketball',
          category: 'sports',
          days: ['Tuesday', 'Thursday'],
          organization: 'School Team',
        },
        {
          id: 'act-9',
          name: 'Volunteer Tutoring',
          category: 'ngo',
          days: ['Saturday'],
          organization: 'Community Education Initiative',
        },
      ],
    },
  },
  {
    id: 'STU-004',
    name: 'Amara Williams',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amara',
    age: 11,
    grade: 'Grade 5',
    guardian: 'James Williams',
    guardianPhone: '+1 (555) 456-7890',
    enrollmentDate: 'Sep 1, 2021',
    status: 'active',
    attendance: 92,
  },
  {
    id: 'STU-005',
    name: 'Sophie Martin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie',
    age: 13,
    grade: 'Grade 7',
    guardian: 'Emma Martin',
    guardianPhone: '+1 (555) 567-8901',
    enrollmentDate: 'Sep 1, 2023',
    status: 'active',
    attendance: 85,
    cpf: '456.789.123-00',
    race: 'branca',
    placeOfBirth: 'Belo Horizonte, MG',
    fatherName: 'Thomas Martin',
    motherName: 'Emma Martin',
    enrollmentOrigin: 'school',
    accompaniedStatus: 'accompanied',
    medicalData: {
      physicalActivityRestrictions: 'No contact sports due to previous concussion',
      dietaryRestrictions: 'Gluten-free diet - celiac disease',
      disabilities: '',
      dentalCare: true,
      ophthalmologicalCare: false,
      allergies: 'Bee stings (severe - carries EpiPen)',
    },
    familyData: {
      members: [
        {
          id: 'fm-5',
          name: 'Emma Martin',
          relationship: 'Mother',
          profession: 'Nurse',
          income: '3,500',
        },
        {
          id: 'fm-6',
          name: 'Thomas Martin',
          relationship: 'Father',
          profession: 'Teacher',
          income: '4,200',
        },
      ],
      maritalStatus: 'separated',
      separated: true,
      contactWithSeparatedSpouse: 'yes',
      contactFrequency: 'weekly',
      housingType: 'own',
      benefits: {
        bolsaFamilia: false,
        rendaCidada: false,
        bpc: false,
        other: '',
      },
      familyAssessment:
        'Parents separated amicably 2 years ago. Sophie maintains regular contact with both parents and transitions smoothly between households. Both parents are actively involved in her education and healthcare needs, particularly managing her celiac disease. No significant behavioral or emotional issues observed.',
      activities: [
        {
          id: 'act-3',
          name: 'Ballet',
          category: 'culture',
          days: ['Monday', 'Wednesday', 'Friday'],
          organization: 'City Ballet Academy',
        },
        {
          id: 'act-4',
          name: 'Art Workshop',
          category: 'socio-educational',
          days: ['Saturday'],
          organization: 'Youth Development Center',
        },
      ],
      socialRisk: {
        childProtectiveServices: false,
        prisonSystem: false,
        policeStation: false,
        emergencyRoom: true,
        rehabilitationCenter: false,
        womensPoliceStation: false,
        otherServices: '',
        hasPrioritySituation: false,
        situationCode: '',
        observations:
          'Sophie was taken to the emergency room twice in the past 6 months due to accidental exposure to gluten, causing severe allergic reactions. Both incidents occurred at social events. Parents now ensure all caregivers and activity organizers are aware of dietary restrictions.',
      },
    },
  },
  {
    id: 'STU-006',
    name: 'Raj Patel',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Raj',
    age: 16,
    grade: 'Grade 10',
    guardian: 'Priya Patel',
    guardianPhone: '+1 (555) 678-9012',
    enrollmentDate: 'Sep 1, 2020',
    status: 'active',
    attendance: 78,
  },
  {
    id: 'STU-007',
    name: 'Emily Johnson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    age: 10,
    grade: 'Grade 4',
    guardian: 'Michael Johnson',
    guardianPhone: '+1 (555) 789-0123',
    enrollmentDate: 'Jan 10, 2024',
    status: 'active',
    attendance: 91,
    cpf: '987.654.321-00',
    race: 'branca',
    placeOfBirth: 'Rio de Janeiro, RJ',
    fatherName: 'Michael Johnson',
    motherName: 'Rebecca Johnson (deceased)',
    enrollmentOrigin: 'social_services',
    accompaniedStatus: 'accompanied',
    medicalData: {
      physicalActivityRestrictions: '',
      dietaryRestrictions: '',
      disabilities: 'ADHD - may need extra time for tasks and quiet environment for testing',
      dentalCare: false,
      ophthalmologicalCare: true,
      allergies: 'Penicillin',
    },
    familyData: {
      members: [
        {
          id: 'fm-7',
          name: 'Michael Johnson',
          relationship: 'Father',
          profession: 'Warehouse Worker',
          income: '2,100',
        },
        {
          id: 'fm-8',
          name: 'Grace Silva',
          relationship: 'Grandmother',
          profession: 'Retired',
          income: '900',
        },
      ],
      maritalStatus: 'single',
      separated: false,
      contactWithSeparatedSpouse: 'no',
      contactFrequency: '',
      housingType: 'ceded',
      benefits: {
        bolsaFamilia: true,
        rendaCidada: true,
        bpc: false,
        other: 'Vale Gás',
      },
      familyAssessment:
        "Single father household with support from grandmother who lives with them. Emily's mother passed away 3 years ago. The family lives in a home provided by the grandmother. Father works evening shifts which sometimes affects homework supervision. Emily receives appropriate ADHD medication and support. The family would benefit from after-school programs to provide structured activities while father is at work.",
      activities: [
        {
          id: 'act-5',
          name: 'Youth Support Program',
          category: 'ngo',
          days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
          organization: 'Hope NGO',
        },
        {
          id: 'act-6',
          name: 'Swimming',
          category: 'sports',
          days: ['Saturday'],
          organization: 'Community Pool',
        },
      ],
      socialRisk: {
        childProtectiveServices: true,
        prisonSystem: false,
        policeStation: false,
        emergencyRoom: false,
        rehabilitationCenter: false,
        womensPoliceStation: false,
        otherServices: 'CRAS - Social Assistance Reference Center',
        hasPrioritySituation: true,
        situationCode: 'FAM-2024-089',
        observations:
          "Family was referred to Child Protective Services following mother's passing to ensure adequate support systems were in place. Social worker visits monthly to monitor Emily's wellbeing and father's capacity to provide care. Situation has stabilized with grandmother's support. Father is cooperative and committed to Emily's care. Family receives regular counseling services through CRAS.",
      },
    },
  },
  {
    id: 'STU-008',
    name: 'Omar Hassan',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Omar',
    age: 17,
    grade: 'Grade 11',
    guardian: 'Aisha Hassan',
    guardianPhone: '+1 (555) 890-1234',
    enrollmentDate: 'Sep 1, 2019',
    status: 'active',
    attendance: 89,
  },
  {
    id: 'STU-009',
    name: 'Isabella Garcia',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella',
    age: 14,
    grade: 'Grade 8',
    guardian: 'Rosa Garcia',
    guardianPhone: '+1 (555) 901-2345',
    enrollmentDate: 'Sep 1, 2022',
    status: 'inactive',
    attendance: 65,
  },
  {
    id: 'STU-010',
    name: 'Lucas Brown',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas',
    age: 18,
    grade: 'Grade 12',
    guardian: 'Sarah Brown',
    guardianPhone: '+1 (555) 012-3456',
    enrollmentDate: 'Sep 1, 2018',
    status: 'graduated',
    attendance: 97,
  },
];
